import streamlit as st
import os
from google import genai
from google.genai import types

# Set up page configurations
st.set_page_config(page_title="Universal AI Medical Expert", page_icon="🩺", layout="centered")

# ==========================================
# 1. INITIALIZE STATE & LLM ROUTINES
# ==========================================
if "page" not in st.session_state:
    st.session_state.page = "input_page"
if "diagnostic_report" not in st.session_state:
    st.session_state.diagnostic_report = None

def query_ai_expert(symptoms_text, user_age, user_gender, api_key):
    """Queries the Gemini API using clinical system instructions to evaluate symptoms."""
    try:
        # Initialize client with the provided API key
        client = genai.Client(api_key=api_key)
        
        system_instruction = (
            "You are an advanced medical diagnostic expert system. Your job is to analyze "
            "patient demographic data and symptoms to provide a structured differential diagnosis. "
            "Always follow this exact output markdown format:\n"
            "## 🎯 Primary Suspected Condition\n[Name of Condition]\n\n"
            "## 📊 Alternative Differential Diagnoses\n- [Alternative 1] (Confidence %)\n- [Alternative 2] (Confidence %)\n\n"
            "## 🛠️ Immediate Actionable Precautions\n- [Precaution 1]\n- [Precaution 2]\n\n"
            "## 🩺 Recommended Medical Specialist\n[Type of Doctor]"
        )
        
        prompt = f"Patient: {user_age} year old {user_gender}.\nSymptoms Reported: {symptoms_text}"
        
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.2, # Low temperature for more deterministic, factual responses
            )
        )
        return response.text
    except Exception as e:
        return f"🚨 **API Error:** {str(e)}"

# ==========================================
# 2. PAGE 1: INTAKE & SYMPTOM SEARCH 
# ==========================================
if st.session_state.page == "input_page":
    st.title("🩺 Universal AI Medical Expert System")
    st.markdown("Describe any combination of symptoms. Powered by Generative AI, this system can analyze across thousands of clinical pathologies.")
    
    st.error("⚠️ **Medical Disclaimer:** This system is an AI prototype for educational purposes. It does not replace professional clinical evaluation or triage.")
    
    st.subheader("📋 Patient Profile & Symptom Intake")
    
    # Secure API Key Entry if not set in environment variables
    env_key = os.environ.get("GEMINI_API_KEY", "")
    if not env_key:
        api_key = st.text_input("Enter your Gemini API Key:", type="password", help="Get a free key from Google AI Studio")
    else:
        api_key = env_key

    col1, col2 = st.columns(2)
    with col1:
        age = st.number_input("Patient Age", min_value=1, max_value=120, value=25)
    with col2:
        gender = st.selectbox("Patient Gender", ["Male", "Female", "Other"])
        
    st.markdown("**Describe everything you are experiencing:**")
    symptoms_input = st.text_area(
        label="Symptom Description Box",
        label_visibility="collapsed",
        placeholder="e.g., I have had a severe throbbing headache behind my left eye for 2 days, accompanied by nausea, sensitivity to bright lights, and a mild stiff neck."
    )
    
    st.markdown("---")
    if st.button("🚀 Run Comprehensive Diagnostic Analysis", type="primary"):
        if not api_key:
            st.error("Please provide a valid Gemini API Key to run the diagnosis.")
        elif len(symptoms_input.strip()) < 10:
            st.warning("Please provide a more detailed description of the symptoms (minimum 10 characters).")
        else:
            with st.spinner("AI Expert Engine processing clinical data matrices..."):
                # Call AI API
                report = query_ai_expert(symptoms_input, age, gender, api_key)
                
                # Save data to session state and switch to the new web page layout
                st.session_state.diagnostic_report = report
                st.session_state.page = "results_page"
                st.rerun()

# ==========================================
# 3. PAGE 2: THE NEW DIAGNOSIS WEB PAGE
# ==========================================
elif st.session_state.page == "results_page":
    st.title("📄 Patient Diagnostic Report")
    st.markdown("Generated dynamically by the Hybrid Expert System Inference Core.")
    st.markdown("---")
    
    # Display the clean markdown output generated by the AI model
    if st.session_state.diagnostic_report:
        st.markdown(st.session_state.diagnostic_report)
    else:
        st.error("No diagnostic data found.")
        
    st.markdown("---")
    st.warning("⚠️ **Reminder:** This report is generated dynamically by an AI entity. Please seek immediate local emergency services if symptoms are severe or life-threatening.")
    
    # Button to clear state and go back to a clean input page
    if st.button("⬅️ Run Another Diagnosis / Go Back"):
        st.session_state.page = "input_page"
        st.session_state.diagnostic_report = None
        st.rerun()